version: "3"
services:
    db:
        image: postgres:13
        environment:
            POSTGRES_DB: dfirtrack
            POSTGRES_USER: ${pg_user}
            POSTGRES_PASSWORD: ${pg_password}
        volumes:
            - db-data:/var/lib/postgresql/data

    dfirtrack:
        build:
            context: ../../
            dockerfile: ./docker/dev/Dockerfile
            args:
                - openssl_o=${openssl_o}
                - fqdn=${fqdn}
                - openssl_ou=${openssl_ou}
        environment:
            - DB_HOST=db
            - DB_USER=${pg_user}
            - DB_PASSWORD=${pg_password}
            - FQDN=${fqdn}
            - SECRET_KEY=${django_secret_key}
            - DISABLE_HTTPS=false
        ports:
            - 80:80
            - 443:443
        depends_on:
            - db
# this is the volume where the dfirtrack repo from the host is mounted to
        volumes:
            - ../../:/dfirtrack/

volumes:
    db-data:
