---
# handlers file for dfirtrack

- name: NGINX | Restart nginx
  service:
    name: nginx
    state: restarted
  become: yes
  become_method: sudo
  ignore_errors: '{{ ansible_check_mode }}'

- name: POSTGRESQL | Restart PostgreSQL
  service:
    name: postgresql
    state: restarted
  become: yes
  become_method: sudo
  ignore_errors: '{{ ansible_check_mode }}'
