name: Lint Ansible

on: [pull_request, push]

jobs:
  lint_ansible:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install ansible ansible-lint
      - run: ansible-lint -x yaml ansible/
